/**
 * The routes for the application
 */
export enum Routes {
  Root = '/',

  // marketing pages
  FAQ = '/#faqs',
  Features = '/#features',
  Subnautica2 = '/games/subnautica-2',
  Subnautica2Beginner = '/games/subnautica-2/beginner-guide',
  Subnautica2Resources = '/games/subnautica-2/resources',
  Subnautica2ResourceChecklist = '/games/subnautica-2/resource-checklist',
  Subnautica2Silver = '/games/subnautica-2/silver',
  Subnautica2SilverIngot = '/games/subnautica-2/silver-ingot',
  Subnautica2Copper = '/games/subnautica-2/copper',
  Subnautica2CopperIngot = '/games/subnautica-2/copper-ingot',
  Subnautica2BasicBattery = '/games/subnautica-2/basic-battery',
  Subnautica2BatteryTerminal = '/games/subnautica-2/battery-terminal',
  Subnautica2AcidicRaionPouch = '/games/subnautica-2/acidic-raion-pouch',
  Subnautica2NecroleiCyst = '/games/subnautica-2/necrolei-cyst',
  Subnautica2MildAcid = '/games/subnautica-2/mild-acid',
  Subnautica2Processor = '/games/subnautica-2/processor',
  Subnautica2Biolab = '/games/subnautica-2/biolab',
  Subnautica2Fabricator = '/games/subnautica-2/fabricator',
  Subnautica2EchoLocation = '/games/subnautica-2/echo-location',
  Subnautica2ModificationStation = '/games/subnautica-2/modification-station',
  Subnautica2EngineEfficiency = '/games/subnautica-2/engine-efficiency',
  Subnautica2CopperWire = '/games/subnautica-2/copper-wire',
  Subnautica2HabitatBuilder = '/games/subnautica-2/habitat-builder',
  Subnautica2Titanium = '/games/subnautica-2/titanium',
  Subnautica2TitaniumIngot = '/games/subnautica-2/titanium-ingot',
  Subnautica2AirTank = '/games/subnautica-2/air-tank',
  Subnautica2OxygenDepth = '/games/subnautica-2/oxygen-depth',
  Subnautica2BasicFins = '/games/subnautica-2/basic-fins',
  Subnautica2ImprovedFins = '/games/subnautica-2/improved-fins',
  Subnautica2Wakemaker = '/games/subnautica-2/wakemaker',
  Subnautica2AdvancedBattery = '/games/subnautica-2/advanced-battery',
  Subnautica2KarakorumPowerPlant = '/games/subnautica-2/karakorum-power-plant',
  Subnautica2PowerPlantObservatory = '/games/subnautica-2/power-plant-observatory',
  Subnautica2PowerCell = '/games/subnautica-2/power-cell',
  Subnautica2VehicleFabricator = '/games/subnautica-2/vehicle-fabricator',
  Subnautica2TadpoleDock = '/games/subnautica-2/tadpole-dock',
  Subnautica2Moonpool = '/games/subnautica-2/moonpool',
  Subnautica2InsufficientSpaceToDock = '/games/subnautica-2/insufficient-space-to-dock',
  Subnautica2Rebreather = '/games/subnautica-2/rebreather',
  Subnautica2ScannerStation = '/games/subnautica-2/scanner-station',
  Subnautica2Beacon = '/games/subnautica-2/beacon',
  Subnautica2RepairTool = '/games/subnautica-2/repair-tool',
  Subnautica2Sulfur = '/games/subnautica-2/sulfur',
  Subnautica2Quartz = '/games/subnautica-2/quartz',
  Subnautica2Glass = '/games/subnautica-2/glass',
  Subnautica2Lithium = '/games/subnautica-2/lithium',
  Subnautica2PlasteelIngot = '/games/subnautica-2/plasteel-ingot',
  Subnautica2Lead = '/games/subnautica-2/lead',
  Subnautica2GermaniumIngot = '/games/subnautica-2/germanium-ingot',
  Subnautica2Gold = '/games/subnautica-2/gold',
  Subnautica2GoldIngot = '/games/subnautica-2/gold-ingot',
  Subnautica2EntangledPowerCell = '/games/subnautica-2/entangled-power-cell',
  Subnautica2Salt = '/games/subnautica-2/salt',
  Subnautica2MetalSalvage = '/games/subnautica-2/metal-salvage',
  Subnautica2Scanner = '/games/subnautica-2/scanner',
  Subnautica2SystemChip = '/games/subnautica-2/system-chip',
  Subnautica2WiringKit = '/games/subnautica-2/wiring-kit',
  Subnautica2AdvancedWiringKit = '/games/subnautica-2/advanced-wiring-kit',
  Subnautica2BioscannerBiomods = '/games/subnautica-2/bioscanner-biomods',
  Subnautica2SonicResonator = '/games/subnautica-2/sonic-resonator',
  Subnautica2AxumVision = '/games/subnautica-2/axum-vision',
  Subnautica2ConduitCrystal = '/games/subnautica-2/conduit-crystal',
  Subnautica2HeatTolerance = '/games/subnautica-2/heat-tolerance',
  Subnautica2AngelComb = '/games/subnautica-2/angel-comb',
  Subnautica2BloomBiofilm = '/games/subnautica-2/bloom-biofilm',
  Subnautica2FeedbackResonator = '/games/subnautica-2/feedback-resonator',
  Subnautica2Celestine = '/games/subnautica-2/celestine',
  Subnautica2CreatureEnamel = '/games/subnautica-2/creature-enamel',
  Subnautica2EnameledGlass = '/games/subnautica-2/enameled-glass',
  Subnautica2Strontium = '/games/subnautica-2/strontium',
  Subnautica2StrongAcid = '/games/subnautica-2/strong-acid',
  Subnautica2FiberMesh = '/games/subnautica-2/fiber-mesh',
  Subnautica2Rubber = '/games/subnautica-2/rubber',
  Subnautica2Tadpole = '/games/subnautica-2/tadpole',
  Subnautica2TadpoleDepthModule = '/games/subnautica-2/tadpole-depth-module',
  Subnautica2BaseBuilding = '/games/subnautica-2/base-building',
  Subnautica2BestBaseLocations = '/games/subnautica-2/best-base-locations',
  Subnautica2Biomes = '/games/subnautica-2/biomes',
  Subnautica2Troilite = '/games/subnautica-2/troilite',
  Subnautica2Atacamite = '/games/subnautica-2/atacamite',
  Subnautica2Mangalloy = '/games/subnautica-2/mangalloy-ingot',
  Subnautica2MetalFarm = '/games/subnautica-2/metal-farm',
  Subnautica2MineralizedClinker = '/games/subnautica-2/mineralized-clinker',
  Subnautica2TroiliteSoftlock = '/games/subnautica-2/troilite-softlock',
  Subnautica2Crafting = '/games/subnautica-2/crafting',
  Subnautica2Map = '/games/subnautica-2/map',
  Subnautica2InteractiveMap = '/games/subnautica-2/interactive-map',
  Subnautica2Vehicles = '/games/subnautica-2/vehicles',
  Subnautica2CreaturesLeviathans = '/games/subnautica-2/creatures-leviathans',
  Subnautica2BaseLocationTierList = '/games/subnautica-2/base-location-tier-list',
  Subnautica2Coop = '/games/subnautica-2/co-op-guide',
  Subnautica2CoopPlayerCount = '/games/subnautica-2/co-op-player-count',
  Subnautica2DedicatedServer = '/games/subnautica-2/dedicated-server',
  Subnautica2SplitScreenCoop = '/games/subnautica-2/split-screen-coop',
  Subnautica2VoiceChat = '/games/subnautica-2/voice-chat',
  Subnautica2Sprint = '/games/subnautica-2/sprint',
  Subnautica2Crossplay = '/games/subnautica-2/crossplay',
  Subnautica2MultiplayerNotWorking = '/games/subnautica-2/multiplayer-not-working',
  Subnautica2InviteNotWorking = '/games/subnautica-2/invite-not-working',
  Subnautica2OnlineServicesConnectionFailed = '/games/subnautica-2/online-services-connection-failed',
  Subnautica2MultiplayerLagDesync = '/games/subnautica-2/multiplayer-lag-desync',
  Subnautica2ControllerNotWorking = '/games/subnautica-2/controller-not-working',
  Subnautica2CoopRejoinAfterHotfix3 = '/games/subnautica-2/co-op-rejoin-after-hotfix-3',
  Subnautica2InteriorWallCostAfterHotfix3 = '/games/subnautica-2/interior-wall-cost-after-hotfix-3',
  Subnautica2NibblersMarrowbreachAfterHotfix3 = '/games/subnautica-2/nibblers-marrowbreach-after-hotfix-3',
  Subnautica2StrikeArmorStackingAfterHotfix3 = '/games/subnautica-2/strike-armor-stacking-after-hotfix-3',
  Subnautica2StartupCrashAfterHotfix3 = '/games/subnautica-2/startup-crash-after-hotfix-3',
  Subnautica2Updates = '/games/subnautica-2/roadmap',
  Subnautica2ReleaseDate = '/games/subnautica-2/release-date',
  Subnautica2Ps5ReleaseDate = '/games/subnautica-2/ps5-release-date',
  Subnautica2Switch2ReleaseDate = '/games/subnautica-2/switch-2-release-date',
  Subnautica2MacReleaseDate = '/games/subnautica-2/mac-release-date',
  Subnautica2XboxGamePass = '/games/subnautica-2/xbox-game-pass',
  Subnautica2OfflineMode = '/games/subnautica-2/offline-mode',
  Subnautica2Price = '/games/subnautica-2/price',
  Subnautica2FreeDownload = '/games/subnautica-2/free-download',
  Subnautica2Cheats = '/games/subnautica-2/cheats',
  Subnautica2Mods = '/games/subnautica-2/mods',
  Subnautica2VrSupport = '/games/subnautica-2/vr-support',
  Subnautica2SystemRequirements = '/games/subnautica-2/system-requirements',
  Subnautica2SteamDeckSettings = '/games/subnautica-2/steam-deck-settings',
  Subnautica2BlackScreenFreezing = '/games/subnautica-2/black-screen-freezing',
  Subnautica2BestSettingsLowFps = '/games/subnautica-2/best-settings-low-fps',
  Subnautica2NotLaunching = '/games/subnautica-2/not-launching',
  Subnautica2GamePassInstallError = '/games/subnautica-2/game-pass-install-error',
  Subnautica2StuckLoadingSave = '/games/subnautica-2/stuck-loading-save',
  Subnautica2SteamDownloadStuck = '/games/subnautica-2/steam-download-stuck',
  Subnautica2SaveFileLocation = '/games/subnautica-2/save-file-location',
  Subnautica2SaveRecoveryCloudSync = '/games/subnautica-2/save-recovery-cloud-sync',
  Subnautica2EarlyAccessWorthIt = '/games/subnautica-2/early-access-worth-it',
  Subnautica2MapSizeBiomes = '/games/subnautica-2/map-size-biomes',
  Subnautica2Hotfix2 = '/games/subnautica-2/hotfix-2',
  Subnautica2Hotfix3 = '/games/subnautica-2/hotfix-3',
  Subnautica2TadpoleParkingAfterHotfix3 = '/games/subnautica-2/tadpole-parking-after-hotfix-3',
  Subnautica2DlssSettingsAfterHotfix3 = '/games/subnautica-2/dlss-settings-after-hotfix-3',
  Subnautica2HammerheadAfterHotfix3 = '/games/subnautica-2/hammerhead-after-hotfix-3',
  Subnautica2FlaresAfterHotfix3 = '/games/subnautica-2/flares-after-hotfix-3',
  Subnautica2SilverAfterHotfix2 = '/games/subnautica-2/silver-after-hotfix-2',
  Subnautica2TroiliteAfterHotfix2 = '/games/subnautica-2/troilite-after-hotfix-2',
  ThumbnailMaker = '/tools/youtube-thumbnail-maker',
  ThumbnailMakerAnchor = '/#thumbnail-maker',
  Inspiration = '/#inspiration',
  Pricing = '/pricing',
  Blog = '/blog',
  Docs = '/docs',
  Ai = '/ai',
  About = '/about',
  Contact = '/contact',
  Waitlist = '/waitlist',
  Changelog = '/changelog',
  Roadmap = '/roadmap',
  CookiePolicy = '/cookie',
  AffiliateDisclosure = '/affiliate-disclosure',
  PrivacyPolicy = '/privacy',
  TermsOfService = '/terms',

  // auth routes
  Login = '/auth/login',
  Register = '/auth/register',
  AuthError = '/auth/error',
  ForgotPassword = '/auth/forgot-password',
  ResetPassword = '/auth/reset-password',

  // dashboard routes
  Dashboard = '/dashboard',

  // admin routes
  AdminUsers = '/admin/users',

  // settings routes
  SettingsProfile = '/settings/profile',
  SettingsBilling = '/settings/billing',
  SettingsCredits = '/settings/credits',
  SettingsSecurity = '/settings/security',
  SettingsNotifications = '/settings/notifications',
  SettingsApiKeys = '/settings/apikeys',

  // payment processing
  Payment = '/payment',
}

/**
 * The routes that can not be accessed by logged in users
 */
export const routesNotAllowedByLoggedInUsers = [Routes.Login, Routes.Register];

/**
 * The routes that are protected and require authentication
 */
export const protectedRoutes = [
  Routes.Dashboard,
  Routes.AdminUsers,
  Routes.SettingsProfile,
  Routes.SettingsBilling,
  Routes.SettingsCredits,
  Routes.SettingsSecurity,
  Routes.SettingsNotifications,
  Routes.SettingsApiKeys,
  Routes.Payment,
];

/**
 * The default redirect path after logging in
 */
export const DEFAULT_LOGIN_REDIRECT = Routes.Subnautica2;
